### ISSUE TITLE
Infinite Map that does not have a dimension limitation

### ISSUE THREAD

**Issue by steenblikrs** [inkandswitch/pushpin#185]
I have found the size constraint of the space to be very limiting. I have filled up whole boards within a few research pushes.

**Comment by pvh** [comment]
Hi Steen, I've got a bit of time to think about this now. Let me know if you're interested in having a conversation about it. I expect you've long-since moved on but if you have some Pushpin boards lying around somewhere I'd be happy to look at some screenshots or something and talk about what might work better.

**Comment by pvh** [comment]
(I'm going to close the issue assuming you're not interested for tracker hygiene purposes but feel free to jump in if you want to take a crack at it.)
